#. Escribe un algoritmo que declare tres variables: una para el nombre de una persona, otra para su edad y otra para su estatura. Asigna valores adecuados a cada una.
print("Haremos un registro, porfavor rellene las siguientes preguntas.")
print("_________________________________________________________________")
nombre1=input("Ingrese el primer nombre: ")
nombre2=input("Ingrese el segundo nombre: ")
apellido1=input("Ingrese el primer apellido: ")
apellido2=input("Ingrese el segundo apellido: ")
edad=int(input("Ingresa la edad que tienes: "))
estatura=int(input("Ingresa tu estatura (cm): "))
print("___________________________________________________________________")
print("")
print(f"-{nombre1} {nombre2} {apellido1} {apellido2} \n-Usted tiene {edad} años \n-Y usted mide {estatura}cm")
print(" ")
print ("*****************************************************")
print ("Muchas gracias")